from enum import Enum, auto


class Good(Enum):
    AGAVE = 0
    AMMO = auto()
    ARMOR = auto()
    AXE = auto()
    BATTLEAXE = auto()
    BLOWGUN = auto()
    BOARD = auto()
    BOW = auto()
    BREAD = auto()
    COAL = auto()
    FISH = auto()
    FLOUR = auto()
    GOAT = auto()
    GOLDBAR = auto()
    GOLDORE = auto()
    GRAIN = auto()
    GUNPOWDER = auto()
    HAMMER = auto()
    HONEY = auto()
    IRONBAR = auto()
    IRONORE = auto()
    LOG = auto()
    MEAD = auto()
    MEAT = auto()
    PICKAXE = auto()
    PIG = auto()
    ROD = auto()
    SAW = auto()
    SCYTHE = auto()
    SHEEP = auto()
    SHOVEL = auto()
    STONE = auto()
    SULFUR = auto()
    SWORD = auto()
    TEQUILA = auto()
    WATER = auto()
    WINE = auto()
    BACKPACKCATAPULT = auto()
    GOOSE = auto()
    EXPLOSIVEARROW = auto()
    SUNFLOWEROIL = auto()
    SUNFLOWER = auto()
